### PR TITLE
Update baseline to 2.249.3

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
@jan-molak I'm trying to get passing tests from commit 36f8e82, but my GitHub Actions aren't running on this PR. I just see "Waiting for checks information..." in the Checks tab. Can you get GitHub Actions working for this branch? Alternatively, if you move this repository from the `jan-molak` GitHub organization to the `jenkinsci` GitHub organization, we can add a `Jenkinsfile` and get the CI/CD for this plugin running on https://ci.jenkins.io/ (preferred).

**Comment by jan-molak** [comment]
Hey @basil - I think the actions should work fine, but I see they're not kicked off because there's a conflict in `.github/workflows/main.yaml`

**Comment by jan-molak** [comment]
I've resolved the conflict, the build has kicked off automatically. Thanks for your help, by the way! I appreciate it

**Comment by basil** [comment]
Oh I see. Sorry for the trouble.

**Comment by basil** [comment]
The acceptance tests for this plugin all depend on the Remoting-based CLI, which was [removed from Jenkins in 2.165](https://www.jenkins.io/blog/2019/02/17/remoting-cli-removed/). To keep this plugin up-to-date with a recent baseline, I have temporarily disabled the acceptance tests.

**Comment by jan-molak** [comment]
@basil - that's fair enough, do you think there's an alternative to Remoting, or would we need to rethink how the acceptance tests work altogether?

**Comment by basil** [comment]
Acceptance tests like this generally belong in the [Jenkins acceptance test harness](https://github.com/jenkinsci/acceptance-test-harness), which has an up-to-date framework for this sort of thing. Within plugins, `JenkinsRule`-based tests with HtmlUnit are the norm, with `RealJenkinsRule` used to test more realistic class loading scenarios.

**Comment by timja** [comment]
> Acceptance tests like this generally belong in the [Jenkins acceptance test harness](https://github.com/jenkinsci/acceptance-test-harness), which has an up-to-date framework for this sort of thing. Within plugins, `JenkinsRule`-based tests with HtmlUnit are the norm, with `RealJenkinsRule` used to test more realistic class loading scenarios.

For plugins like this I don't think they would go to the acceptance test harness but you can use the framework in your plugin, see warnings-ng plugin as an example:

https://github.com/jenkinsci/warnings-ng-plugin/blob/master/ui-tests/pom.xml#L28

**Pull request merged**
