### PR TITLE
Show disabled and not-yet-built jobs in gray color

### PR DESCRIPTION
**Pull request by matoxp**

### CODE REVIEW

**Comment by jan-molak** [comment]
Thanks for your contribution, @matoxp.

I'm not sure about using `.isBuildable` to determine if a build job is disabled. If I remember correctly, `.isBuildable` is used in Jenkins to toggle the 'build now' icon. Which means that if the user is not permitted to build a job, `isBuildable` returns false even if the job is not actually disabled.

Seems like using [`AbstractProject::isDisabled`](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/AbstractProject.java) could be a safer bet.

(note to self: fix related to request #90)

**Comment by matoxp** [comment]
Jan, I just had a look at `AbstractProject::isBuildable`:

    @Override
    public boolean isBuildable() {
      return !isDisabled() && !isHoldOffBuildUntilSave();
    }

This is *not* refined in subclasses of `AbstractProject`, so user permissions have no influence.

**Comment by jan-molak** [comment]
OK, would you still like to see this merged in? I see you've closed the request?

**Comment by matoxp** [comment]
Please do merge. Me closing the request was an accident.

**Comment by mbyrne00** [comment]
Hey - any reason for this not being merged in? Would be very handy as we've had some disabled builds go unnoticed.

**Pull request merged**
