### PR TITLE
Show failure descrition rather than name from Build Failure Analyzer

### PR DESCRIPTION
**Pull request by Witos**
Currently, Build Monitor shows name of the failure from the Build Failure Analyzer. IMHO showing description would be more useful, since it uses placeholders which can be used to pass a message with more detailed info to the monitor.

### CODE REVIEW

**Comment by jan-molak** [comment]
Thanks for your contribution, @Witos!

@patrickdepinguin - what's your view on that?

**Comment by patrickdepinguin** [comment]
@Witos @jan-molak  I think this best would be a configurable option: in my case the build monitor screen is relatively small and even with ~10 jobs we are already running against space issues such that we need to carefully design the job display names, hide culprits, ...

So in our case, showing the description would become too much, but I can see the value of the description for other users.

**Comment by Witos** [comment]
OK, will make it an option.

**Comment by drekbour** [comment]
+1 for optional. I would go further and say the default should remain the name. When I added BFA support, I looked at what is presented for BFA elsewhere in Jenkins and decided the name field only has value if it is meant to tersely summarise the fail. This fits with the concept of a heads-up monitor.

We have full text in our descriptions that serves as instructions on how to resolve certain environmental issues. No way that is intended for the monitor.

**Comment by arpitgold** [comment]
+1 for this MR.
Do you have any plans to merge it in master?

**Comment by drekbour** [comment]
I've just noticed BFA can now parameterise the Description field with regex capture elements from the log scraping. This makes the description _much_ more powerful and maybe I would now like to use it as the primary display and move the "how to resolve" text into the comment section.

+1

**Comment by jan-molak** [comment]
Cool, sounds good

**Pull request closed without merging**
