### PR TITLE
Listing all current (building) builds

### PR DESCRIPTION
**Pull request by dcendents**
Hi,

Now that I use Jenkins pipelines, it is common that I have multiple builds of a job running at the same time. This is not unique to pipelines though, it was possible to set a job to run concurrent builds before, but now pipelines makes it the default behavior.

I have effectively split `KnowsLastBuildDetails` in two
  1. `KnowsLastCompletedBuildDetails`, which deals with the last completed build
  1. `KnowsCurrentBuildsDetails`, which return a list of all the builds currently building

I have added some unit tests but I did not add an acceptance test as I would need to test the interface while multiple jobs are building and I'm not sure if it is a good idea.

Please review it and let me know what you think.

Cheers,
Dan

### CODE REVIEW

**Comment by jan-molak** [comment]
Will do thanks for your contribution!

**Comment by ChadiEM** [comment]
Related to #174 ?

**Comment by dcendents** [comment]
@ChadiEM yes it is partly related but not totally.

It will display the progress (time) of all the builds but the "visual feedback" behavior is unchanged. The color still displays the result of the last completed build.

There is still a single progress bar which shows the progress of the more recent build.

Here is ascreenshot:
builds

 I consider it a step forward to issue #174

**Comment by erikhakansson** [comment]
We're running a locally built version with this PR at work. It works great! It would be nice to have it merged as soon as possible!

**Pull request merged**
