### PR TITLE
Show date of last build

### PR DESCRIPTION
**Pull request by jzmodmed**
Hey,

Awesome project! Failing builds are bad, but what is really bad are builds that aren't running. If you added a date of last build feature it would help a ton.

Thanks!
Jimmy

### CODE REVIEW

**Comment by mfriedenhagen** [comment]
+1

**Comment by stephencsmall** [comment]
+1 for this enhancement.

**Comment by bernardomaciel** [comment]
+1

**Comment by mfriedenhagen** [comment]
BTW: -0 for the patch. The patch will update the interval since the last build every 5 seconds. On a screen with 24 jobs this is quite noisy. I would suggest either switching to updating the interval every n minutes only or to just provide a static timestamp, which would be sufficient for my needs.

**Comment by jan-molak** [comment]
@jzmodmed, @kstevens  - I've just implemented a fix based on your feedback and the pull request. 
I'd love to hear what you, @KamuiShiro, @owenmead, @lapozzo, @highflying, @mfriedenhagen, @stephencsmall, @bernardomaciel and others think about [the latest build](https://smartcode-opensource.ci.cloudbees.com/job/jenkins-build-monitor-plugin/140/artifact/target/build-monitor-plugin.hpi).

Looking forward to your feedback!
Jan

**Comment by stephencsmall** [comment]
Looking perfect on my test Jenkins server. I like the use of a relative "X days/hours/minutes ago" type display.  This makes it easily readable on the fly.

Can't wait until it goes into update center so we can put it on our production instance!

**Comment by mfriedenhagen** [comment]
Looks good for me.

**Comment by sandeep789** [comment]
+1

**Pull request closed without merging**
