### PR TITLE
Move settings to config page as default #119

### PR DESCRIPTION
**Pull request by tcollignon**
This is PR2 of #119.

This is my first contribution of this plugin, so tell me all the problems with this PR, and I will fix it.

I have try to give tests, but I'm not sure it's ok for you.

Thanks

### CODE REVIEW

**Comment by jan-molak** [comment]
Thanks @tcollignon! I'm currently working on addressing #124, #165 and #57 and will review your PR as soon as I'm done with those.

Best,
Jan

**Comment by tcollignon** [comment]
Hi, any news here?

**Comment by erikhakansson** [comment]
This would be very welcome

**Comment by hughsaunders** [comment]
Resolved the conflicts in a new PR: https://github.com/jan-molak/jenkins-build-monitor-plugin/pull/413

**Pull request closed without merging**
