### PR TITLE
Feature: Ability to hide header and footer

### LINKED ISSUE #38: Possibility to hide board title
Hi,
it would be nice to be able to hide board title. I think it's a bit unnecessary when I have only one display. It'll be cleaner with more space for jobs.
thanks
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25288141-possibility-to-hide-board-title?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by drekbour**
Cookie-based checkbox added to settings panel which hides the header and footer
(now rebased onto master to include similar work on a colour-blind checkbox)
Closes #38

### CODE REVIEW

**Comment by Brantone** [comment]
For the `<notifier />` directive issue, I wonder if that could be placed outsider the footer and hidden until it's needed?

**Comment by drekbour** [comment]
@jan-molak, I keep requiring to rebase and patch up to keep this current. Is there a problem with integrating it? It's a year old now!
I've corrected the Notifier issue...

**Comment by drekbour** [comment]
@jan-molak, I've rebased this again. Can you *please* review and integrate (or say why you don't like the feature) - it's been ~20 months now.

**Comment by jan-molak** [comment]
Hi @drekbour and apologies for not getting back to you sooner.

I think that the underlying problem here is that Build Monitor didn't cope very well with a large number (hundreds) of projects displayed on one screen - as depicted on the screenshot attached to #124.
That's because I've never anticipated people using it to monitor so many things! :smile: 

Having said that, many thanks for your pull request. It served as a valuable reminder that the problem needed to be addressed. It also highlighted that the UI required a bit of a rework to make it more flexible and capable of supporting busy Jenkins installations, such as yours.

I've incorporated suggestions from yourself, @saan800 (#124) and @davidparsson (#165) and came up with a number of changes to the UI that should hopefully address the points you guys have raised. 

If you have a moment, I'd be grateful if you could [download the latest build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/13/artifact/target/build-monitor-plugin.hpi), try it out and let me know your thoughts!

All the best,
Jan

**Comment by drekbour** [comment]
I tried the latest build and it's fine but I can't comment on the efficacy for large volumes as our usecase is *not* "200 jobs". We resolved that one years ago by allowing the use of filters from the ListView so it can monitor failed/building jobs only. We have many more usecases speaking to why screen real-estate matters:
1. The master build monitor is on a small screen at the end of long desk (politics...). It may only have a few items on but I don't want nn% of the vertical space taken by static content making me squint harder. 
2. Users often open a local build monitor in a window on their desktop (with perhaps a more personalised set of jobs)
3. We may yet add this as a kind of "iframe/portlet" in a much broader-scoped dashboard
4. We want information that is relevant to our dev process. Green is good; Red is bad; Title, logo, plugin version, homepage and author are noise.

I worry point 4 (the only one that really matters) is clashing with some other concern?

**Pull request closed without merging**
