### PR TITLE
WIP: Workflow support

### LINKED ISSUE #143: Workflow Jenkins Plugin builds support
It would be great to provide Workflow Jenkins Plugin builds compatibility.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11892385-workflow-jenkins-plugin-builds-support?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gregsymons**
I _think_ all that's needed is some type migration from `AbstractProject` to `Job<?, ?>`. I've done the changes, but haven't got the tests running locally yet. 

Fixes #143

### CODE REVIEW

**Comment by gregsymons** [comment]
So I've gotten the tests running locally, and only one of them fails, but it fails on master, too: `displays_potential_failure_cause_when_it_is_known`. Looking more closely, that part of the code was already using Jobs, and given that it fails for me on master, I don't think my changes impacted it. It could be something about my local config.

**Comment by gregsymons** [comment]
Also, using it in my jenkins, the workflow builds now show up!

**Comment by mildju** [comment]
Philippe Lambert will be out of the office starting  09/07/2015 and will be
returning on 23/07/2015.

Hello,

I'm currently out of the office.  Your mail won't be forwarded but I will
respond to your message as soon as I'll be back.

For urgent matters related to CmaXOnline, please check with St�phane
Jantzen.
For urgent matters related to the Testing Tool, please check with Pierre
Hoffmann.

Cheers,
Philippe

----------------------------------------------------------------------------

Clearstream Services S.A.
42 Avenue JF Kennedy, L-1855 Luxembourg
Soci�t� anonyme is organised with limited liability
in the Grand Duchy of Luxembourg R.C.S. Luxembourg B 60911.

-----------------------------------------
Visit us at http://www.clearstream.com

IMPORTANT MESSAGE

Internet communications are not secure and therefore Clearstream International does not accept legal responsibility for the contents of this message.

The information contained in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any views expressed in this e-mail are those of the individual sender, except where the sender specifically states them to be the views of Clearstream International or of any of its affiliates or subsidiaries.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

END OF DISCLAIMER

**Comment by jan-molak** [comment]
Hey @gregsymons - all the tests, including the one you mentioned should be passing correctly (as per the [CI build](https://smartcode-opensource.ci.cloudbees.com/)).

What are the errors you're seeing?

**Comment by gregsymons** [comment]
Selenium is throwing a `StaleElementReferenceException` while searching for the failure cause. The full test log is below. Watching it interact with Chrome, I don't see the failure cause element on the screen, but it could be because it went by too fast. Is there a way to get the test framework to take a screenshot automatically on a failure? Or if it does, where do the screenshots go?

```
-------------------------------------------------------------------------------
Test set: com.smartcodeltd.jenkinsci.plugins.buildmonitor_acceptance.BehaviourWithBuildFailureAnalyserTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 28.01 sec <<< FAILURE!
displays_potential_failure_cause_when_it_is_known(com.smartcodeltd.jenkinsci.plugins.buildmonitor_acceptance.BehaviourWithBuildFailureAnalyserTest)  Time elapsed: 27.773 sec  <<< ERROR!
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=43.0.2357.132)
  (Driver info: chromedriver=2.16.333243 (0bfa1d3575fc1044244f21ddb82bf870944ef961),platform=Mac OS X 10.10.4 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.04 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.37.0', revision: 'a7c61cbd68657e133ae96672cf995890bad2ee42', time: '2013-10-18 09:51:02'
System info: host: 'Gregs-MBP.local', ip: '172.24.0.143', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.7.0_80'
Session ID: afe60a3d6f064c0e9ab149896d921df4
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/0h/8f6sk7hx6x59f_myrv0fy60h0000gp/T/.org.chromium.Chromium.b4iH0i}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=43.0.2357.132, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:554)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:171)
	at org.openqa.selenium.remote.RemoteWebElement.findElementByClassName(RemoteWebElement.java:228)
	at org.openqa.selenium.By$ByClassName.findElement(By.java:393)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:167)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor_acceptance.pageobjects.buildmonitor.Job.possibleFailureCause(Job.java:22)
	at com.smartcodeltd.jenkinsci.plugins.buildmonitor_acceptance.BehaviourWithBuildFailureAnalyserTest.displays_potential_failure_cause_when_it_is_known(BehaviourWithBuildFailureAnalyserTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.jvnet.hudson.test.JenkinsRule$2.evaluate(JenkinsRule.java:473)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
```

**Comment by gregsymons** [comment]
Is there anyway we can get your CI set up to build pull requests? Because I think this test failure is just something weird in my environment that I can't quite chase down.

**Comment by jan-molak** [comment]
> Selenium is throwing a StaleElementReferenceException while searching for the failure cause. The full test log is below. 

Interesting! Maybe we need to wait for the element to show up before the assertion in the [Job PageObject](https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/306d89806a9916ab43fbbd6e6cd8b847eebe1e9f/src/test/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor_acceptance/pageobjects/buildmonitor/Job.java) to make the result more predictable ([some example implementations](https://gist.github.com/djangofan/5112655))

> Watching it interact with Chrome, I don't see the failure cause element on the screen, but it could be because it went by too fast.

You could run the tests in debug mode in your IDE to step through them.

> Is there a way to get the test framework to take a screenshot automatically on a failure? Or if it does, where do the screenshots go?

It doesn't at the moment as the CI tests are [executed on SauceLabs](https://saucelabs.com/u/build-monitor).
This capability [could be added though](http://blogs.steeplesoft.com/posts/2012/grabbing-screenshots-of-failed-selenium-tests.html) 

---

Note to self:
- [ ] review how Selenium is set up to wait for an element to show up
- [ ] set up a [pull request builder](http://documentation.cloudbees.com/docs/cje-user-guide/pull-request-builder-for-github-sect-overview.html) so that contributors can benefit from SauceLabs tests too

**Comment by gregsymons** [comment]
Actually, after doing a little bit of digging, it may be because the claim plugin doesn't work with Run and Job; this is why that plugin doesn't work with the workflow plugin, too. I'm not 100% sure on that, though.

**Comment by gregsymons** [comment]
Err, not claim, but failure cause.

**Comment by davidparsson** [comment]
I have seen the `StaleElementReferenceException` as well, and I found it to be because the acceptance tests didn't wait for the builds to complete, but expecting them to be completed.

I saw this in the test that should display the failure cause, and since the build was still in progress when the build monitor was loaded, the failure cause element was removed, causing the exception. A fix for this is waiting in #169.

**Comment by jan-molak** [comment]
#169 has now been merged; @gregsymons could you please have another look?

**Comment by jan-molak** [comment]
@gregsymons - I spent some time trying to understand what's required to support the workflow plugin, and the shopping list looks more or less like this:
- [ ] the changes you've already suggested - this shouldn't cause any negative impact
- [ ] plus we'd need to update the dependency on Jenkins core to 1.580.1 (as per the [compatibility page](https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md#jenkins-core-dependency)) - this seems fairly straight-forward as this LTS build is [popular enough](http://stats.jenkins-ci.org/jenkins-stats/svg/201307-jenkins.svg)
- [ ] however, you seem to be right and Build Failure Analyzer would need to be updated to support the newer core (as per [JENKINS-27123](https://issues.jenkins-ci.org/browse/JENKINS-27123) and the [compatibility page](https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md#miscellaneous)); I've already voted for [JENKINS-27123](https://issues.jenkins-ci.org/browse/JENKINS-27123) but am not sure how much time/work is required to fix it

**Comment by jan-molak** [comment]
It's looking good! Thanks for your contribution @gregsymons :+1:

**Comment by mildju** [comment]
Philippe Lambert will be out of the office starting  29/08/2015 and will be
returning on 02/09/2015.

Hello,

I'm currently out of the office.  Your mail won't be forwarded but I will
respond to your message as soon as I'll be back.

For urgent matters related to CmaXOnline, please check with St�phane
Jantzen.
For urgent matters related to the Testing Tool, please check with Pierre
Hoffmann.

Cheers,
Philippe

----------------------------------------------------------------------------

Clearstream Services S.A.
42 Avenue JF Kennedy, L-1855 Luxembourg
Soci�t� anonyme is organised with limited liability
in the Grand Duchy of Luxembourg R.C.S. Luxembourg B 60911.

-----------------------------------------
Visit us at http://www.clearstream.com

IMPORTANT MESSAGE

Internet communications are not secure and therefore Clearstream International does not accept legal responsibility for the contents of this message.

The information contained in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it, is prohibited and may be unlawful. Any views expressed in this e-mail are those of the individual sender, except where the sender specifically states them to be the views of Clearstream International or of any of its affiliates or subsidiaries.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

END OF DISCLAIMER

**Comment by davidparsson** [comment]
Does this mean that this plugin now requires Jenkins Core v1.580.1? As far as I can tell, that's not reflected in the `pom.xml` file.

**Comment by jan-molak** [comment]
Hey @davidparsson, no, I thought that it might be required after reading the [compatibility page](https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md#jenkins-core-dependency), but it turns out that some basic support can be achieved without upgrading the core (see update 2 to my comment above).

What I'd still like to do though is to display the current stage of the pipeline while it's in progress.

**Comment by davidparsson** [comment]
That's good to know, since we're still on an older version. Thanks.

**Comment by jan-molak** [comment]
No worries, is there anything preventing you from upgrading to 1.580.1? I think it might be required to display the currently executed stage of the pipeline though.

**Pull request closed without merging**
