### PR TITLE
Add default settings to Build Monitor Views

### PR DESCRIPTION
**Pull request by timbrown5**
- Added settings items to config so default settings can be tracked
  in the plugin, not just the cookie.
- Updated configure-entries.jelly to allow setting of the settings.
- Updated main.settings.jelly to pass default settings from plugin to
  settings.js. Also added a new button to reset settings in cookie to
  default.
- Updated settings.js to use the default settings provided by
  main.settings.jelly. Also added a function to reset settings cookie
  to the default value.

### CODE REVIEW

**Comment by timbrown5** [comment]
I don't think these are test failures I have introduced (I got similar failures on my local machine when doing `mvn install` on the master branch). Is there a way to check that the job works with the master branch?

**Comment by MarkTickner** [comment]
Looks good, thanks for fixing my issue 🙂

**Comment by timja** [comment]
Merge in master to hopefully get a passing CI

**Comment by timbrown5** [comment]
Thanks. I am away at the moment, but will try when I get back next week.

**Comment by timbrown5** [comment]
Looks like some tests failed again. Looks like there are a lot of `[SEVERE]: bind() failed: Cannot assign requested address (99)` but I assume this is okay (despite being labels as `SEVERE`?

Is there an easy way to run specific tests locally? If so maybe I can fix the tests in my branch before uploading again.

**Comment by timja** [comment]
> Looks like some tests failed again. Looks like there are a lot of `[SEVERE]: bind() failed: Cannot assign requested address (99)` but I assume this is okay (despite being labels as `SEVERE`?
> 
> Is there an easy way to run specific tests locally? If so maybe I can fix the tests in my branch before uploading again.

Looks like the merge didn't go properly? there's lots of things you didn't change in the files changed page

**Pull request closed without merging**
