### PR TITLE
Restore support for Groovy Postbuild plugin

### PR DESCRIPTION
**Pull request by basil**
Support for this plugin seems to have been removed in recent commits, but I see no reason why we can't add it back. @dcendents do you see any problem with this?

### CODE REVIEW

**Comment by dcendents** [comment]
@basil AFAIK I originally added it when I worked on adding badges to the build monitor view. Now that the feature has been moved in the badge plugin and we bumped the minimum version to 2.289.1, I didn't think we still need the groovy postbuild plugin.

If I get it right, in recent jenkins version, if we use the groovy postbuild plugin to add badges (manager.addShortText in pipeline), it only translate the call to the badge plugin.

Now that I'm writing that, I'm not sure I added an optional dependency on the badge plugin, which might be the real problem.

**Comment by basil** [comment]
@dcendents I trust your judgment. I've never actually used this plugin; I'm just a Jenkins core maintainer. So should this PR be closed?

**Comment by dcendents** [comment]
Yes I checked and there is a dependency on the badge plugin, which is all we need to support:

```xml
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>badge</artifactId>
            <version>1.9</version>
            <optional>true</optional>
        </dependency>
```

I'm not sure I understand the motivation behind this PR, so if you thought the groovy postbuild was removed by mistake, it wasn't, it was deliberate and yes we can close this PR.

**Comment by basil** [comment]
> I'm not sure I understand the motivation behind this PR, so if you thought the groovy postbuild was removed by mistake, it wasn't, it was deliberate and yes we can close this PR.

Yeah, I thought it was just an oversight. Since it's not, let's close this PR. Thanks for looking into it!

**Pull request closed without merging**
