### PR TITLE
Add default settings to Build Monitor Views

### LINKED ISSUE #71: Feature request: allow customizing the default settings
The plugin has a fixed default configuration, and stores user-made changes in a cookie. This works fine when displaying the build monitor view on a controllable display.
However, when displaying it on a system without keyboard/mouse, like a web kiosk, modifying the configuration so it would be stored in the cookie is problematic.
Being able to set the default configuration in absence of a cookie could cover this scenario.
I currently worked around this by manually editing the javascript files, but this is not very nice.
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3133560-feature-request-allow-customizing-the-default-settings?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #119: Move settings to config page as default?
Wondering if it's worth moving the settings to the config page to be utilized as default, while still allowing settings to store cookies and override defaults?

Reason: I've had a few monitors set up, get them all configured to look pretty, then show it on a different computer and the columns/text-size is garbled again.
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7546837-move-settings-to-config-page-as-default?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #227: Persist UI configuration
Jan, its really a great plugin to simplify workflow view. 

It would really help if we could persist the UI configuration (say: a default configuration), which shows up consistently same on all machines, and if user needs a custom one he can override it for a particular screen. Currently since this is stored in cookies, each member in the team needs to adjust their views + each time we clear cookies, its all reset.
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34902195-persist-ui-configuration?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #315: 8 columns not enough
I love your plugin! It is awesome.
But I need more "Maximum number of columns". Values are 1 to 8 but I would really need 16 or so.

Do you think it is feasible to have that limit raised?
capture
?

Dekuju,
Oscar

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/45718141-8-columns-not-enough?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F580790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #409: Number of columns configurable
We use this plugin in our automated jenkins deployment, which means that any config not persisted is lost. The 'number of columns' is stored as a cookie which makes it impossible to automate. Could there be a default value for this to be set to in the Configure screen?

### PR DESCRIPTION
**Pull request by dcendents**
This is a "rebase" of #425

Now using the view config page, any positive value can be set for font size and number of columns. (Which is a good thing as poeple did not always like the current limitations, who are we to say what looks better on their monitor).

To reflect that, I have also increased the sliders in the Settings panel, font size 0.1 to 5 (was 2), number of columns 1 to 20 (was 8). These are still arbitrary values but I did not want to change the slider so I had to set something that seems reasonable.

After this is merged we can close the following PRs and issues: 

Fixes #425 
Fixes #413
Fixes #409 
Fixes #315 
Fixes #227
Fixes #189
Fixes #119
Fixes #71

### CODE REVIEW

**Review by basil — APPROVED** [review]
Thanks for the PR! Looks good to me, but I will wait a day or two in case @jan-molak wants to comment.

**Comment by jan-molak** [comment]
Thanks for working on this, @dcendents, and thanks for the ping @basil. 
LGTM :shipit:

**Comment by basil** [comment]
@dcendents There are 4 new test failures in the CI build for this PR. I ran the build twice, and the 4 new failures were present both times.

**Comment by basil** [comment]
@dcendents I would like to extend an open invitation for you to become a (co-)maintainer of this plugin along with Jan and I, if you are interested. You have been the most prolific contributor to this plugin, and it would be great to have you on board to keep this plugin healthy moving forward.

**Comment by dcendents** [comment]
Thanks @basil and @jan-molak , I'd be glad to join you and help maintain this plugin. Let me know what I need to do to make it official.

**Pull request merged**
