### PR TITLE
Added sorting by estimated duration...

### PR DESCRIPTION
**Pull request by eribau**
...of a job that also takes into account eventual upstream jobs' estimated durations.

### CODE REVIEW

**Comment by jan-molak** [comment]
Hey @eribau and thanks for the PR, did you mean to close it?

**Comment by eribau** [comment]
Hi. No, I didn't really mean to close it. First time i'm making a pull request and I noticed that I needed to add a commit to it so I closed it, but I realized that github adds new commits automatically. D'oh!

**Comment by jan-molak** [comment]
No worries :-) The PR looks legit, thanks for your contribution @eribau!

**Comment by jan-molak** [comment]
No worries :-) The PR looks legit, thanks for your contribution @eribau!

**Pull request merged**
